--------------------------------------------------------
--  File created - Monday-December-02-2024   
--------------------------------------------------------
@C:\Adsoleil\Github\ora_sql\etl_dev\COH_WWO_EAM_EXTRACT_20240821.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\DELETED_ASSETS_20240821.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\DWO_ASSET_REGISTER.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\DWO_ASSET_TYPES.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\DWO_COST_OVERRIDE.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\M_CLASS_CONDITION_Q_LOOKUP.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\M_CLASS_LOOKUP_V1.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\M_DWO_ASSET_TYPES_V1.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\M_DWO_CLASS_CATEGORY_ASSET_V1.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\M_DWO_COST_OVERRIDE.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\M_UNIT_CLASS_ASSET_LOOKUP_V1.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\RAW_COH_ASSET_LIVE_EAM_TB2_20240821.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\RAW_COH_ASSET_LIVE_NEW_TB1_20240821.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\TEMPLATE_ASSET_REGISTER_20240821.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\TEMPLATE_ASSET_REGISTER_20240824.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\TEMPLATE_ASSET_TYPES_20240821.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\TEMPLATE_COST_OVERRIDE_20240821.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\WWO_CLEAN_ASSET_REGISTER_V1.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\WWO_CLEAN_ASSET_REGISTER_V2.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\WWO_EAM_SYSTEM_EXTRACT_V1.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\WWO_RAW_TAB1_V1.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\WWO_RAW_TAB2_V1.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\COH_WWO_EAM_EXTRACT_20240821_PK.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\WWO_RAW_CLASSES_20240821_PK.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\TEMPLATE_ASSET_REGISTER_20240821_PK.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\COH_WWO_EAM_EXTRACT_20240821_CONSTRAINT.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\M_CLASS_LOOKUP_V1_CONSTRAINT.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\TEMPLATE_ASSET_REGISTER_20240821_CONSTRAINT.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\TEMPLATE_ASSET_REGISTER_20240824_CONSTRAINT.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\WWO_CLEAN_ASSET_REGISTER_V1_CONSTRAINT.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\WWO_CLEAN_ASSET_REGISTER_V2_CONSTRAINT.sql
@C:\Adsoleil\Github\ora_sql\etl_dev\WWO_EAM_SYSTEM_EXTRACT_V1_CONSTRAINT.sql
