--------------------------------------------------------
--  Constraints for Table M_CLASS_LOOKUP_V1
--------------------------------------------------------

  ALTER TABLE "COH_DEV"."M_CLASS_LOOKUP_V1" MODIFY ("CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "COH_DEV"."M_CLASS_LOOKUP_V1" ADD CONSTRAINT "WWO_RAW_CLASSES_20240821_PK" PRIMARY KEY ("CLASS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
