--------------------------------------------------------
--  Constraints for Table TEMPLATE_ASSET_REGISTER_20240821
--------------------------------------------------------

  ALTER TABLE "COH_DEV"."TEMPLATE_ASSET_REGISTER_20240821" MODIFY ("ASSET_ID" NOT NULL ENABLE);
  ALTER TABLE "COH_DEV"."TEMPLATE_ASSET_REGISTER_20240821" ADD CONSTRAINT "TEMPLATE_ASSET_REGISTER_20240821_PK" PRIMARY KEY ("ASSET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
